### ISSUE TITLE
line 67

### ISSUE THREAD

**Issue by gustavotate** [Dniel97/orpheusdl-tidal#1]
File "orpheus.py", line 67
    raise Exception(f'Unknown setting "{modulesetting}" for module "{setting}"')
                                                                              ^
SyntaxError: invalid syntax

**Comment by Dniel97** [comment]
Which python version are you using? Remember to use Python 3.7+

**Comment by Dniel97** [comment]
No further information provided, closing.

**Comment by gustavotate** [comment]
3.10

**Comment by Dniel97** [comment]
Could you show the complete error message with a screenshot?

**Comment by gustavotate** [comment]
<img width="737" alt="Captura de Pantalla 2021-12-04 a la(s) 10 33 56" src="https://user-images.githubusercontent.com/45040254/144711444-d4e30908-0f0d-4610-838f-b486af61cc2e.png">

Im stuck here...

**Comment by Dniel97** [comment]
Follow step 2. https://github.com/yarrm80s/orpheusdl#installation

`pip install -r requirements.txt`

**Comment by gustavotate** [comment]
Works awesome!
Thank you!
