### ISSUE TITLE
Does OrpheusDl-Tidal downlad 360 files with 24 channels?

### ISSUE THREAD

**Issue by KatieBelli** [Dniel97/orpheusdl-tidal#13]
Downloaded this track: https://tidal.com/browse/track/235510761

I used https://github.com/ittiam-systems/libmpegh to decode it and then XRECODE 3 to convert it into seperate channels.

But it only gives me 12 mono channels. Shouldn't it be 24 mono channels?

**Comment by Dniel97** [comment]
Tidal uses Sony 360 Reality Audio L1 which supports a 7.1.4 channel layout with 10 objects and a datarate of 667 kbps. If you want 24 channels you would need Sony 360RA L3 which supports a 22.2 channel layout with 24 objects and a datarate of 1,5 Mbps but Tidal only delivers and supports L1.

**Comment by hell001** [comment]
@yarrm80s @Dniel97 Apologies for the bump, but it's not easy to find other people that are familiar with the kinds of 360RA. Since Deezer no longer offers 360, are there any other services that offer L3?

**Comment by Dniel97** [comment]
Only TIDAL, Amazon Music and Nugs.net. Amazon Music also supports 24 channels, not sure if bugs.net also supports 24 channels.

**Comment by hell001** [comment]
@Dniel97 Thanks for the quick response. Are there any modules or other programs that can rip from Nugs.net or Amazon?

**Comment by Dniel97** [comment]
At least nugs.net is available but not actively maintained: [https://github.com/Dniel97/orpheusdl-nugs](https://github.com/Dniel97/orpheusdl-nugs)
