### ISSUE TITLE
Weird assertion error after attempting to create a Mobile session

### ISSUE THREAD

**Issue by zaneburko** [Dniel97/orpheusdl-tidal#14]
When I try to start a new "rip", it asks me if I'd like to create a new mobile session as I have not created one already. It asks for my username and password which I put in correctly. Once the process starts, it gets interrupted very quickly due to an assertion error. I've tried reinstalling Orpheus, reinstalling the modules, installing the modules manually by cloning the repos, and nothing seems to work. 

I'm not sure what this means as I have little understanding of python. Anyone know how to fix this. My endgoal is to be able to obtain 360 audio and I'm not sure what is causing this issue. 
 
![image](https://user-images.githubusercontent.com/36136355/183313399-e6efd06b-3b12-47e9-86a1-f01805b4ab83.png)

 
  ____             _                    _____  _      
  / __ \           | |                  |  __ \| |     
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |     
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |     
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____ 
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |                                       
             |_|                                       
             

 "enable_mobile" is enabled but no MOBILE session was found. Do you want to create a MOBILE session (used for AC-4/360RA) [Y/n]? Y
 TIDAL: Creating a Mobile session
 TIDAL: Enter your Tidal username and password:
 Username: _______@gmail.com
 Password: 
Traceback (most recent call last):
  File "/Users/zaneburko/orpheusdl/orpheus.py", line 223, in <module>
    main()
  File "/Users/zaneburko/orpheusdl/orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/Users/zaneburko/orpheusdl/orpheus/core.py", line 360, in orpheus_core_download
    music = orpheus_session.load_module(mainmodule)
  File "/Users/zaneburko/orpheusdl/orpheus/core.py", line 205, in load_module
    loaded_module = class_(module_controller)
  File "/Users/zaneburko/orpheusdl/modules/tidal/interface.py", line 111, in __init__
    sessions[session_type].auth(username, password)
  File "/Users/zaneburko/orpheusdl/modules/tidal/tidal_api.py", line 454, in auth
    assert (r.status_code == 200)
AssertionError

  - OS: Monterey
  - Python version 3.10.6

**Comment by Dniel97** [comment]
I was not able to reproduce this behavior on macOS Big Sur with Python 3.9.x using multiple accounts. I'd suggest using Python 3.9.x instead of Python 3.10 but other than that I have no idea what's going on. Set `"debug_mode": true,` inside config/settings.json and try it again, maybe that helps understanding the error.

**Comment by HoodPharmacist** [comment]
experiencing this "AssertionError" as well with Python Version 3.9.7

**Comment by Dniel97** [comment]
> experiencing this "AssertionError" as well with Python Version 3.9.7

Can you also enable `debug_mode` and share the output while trying to create a mobile session?

**Comment by HoodPharmacist** [comment]
Of course! Here is the output
![Capture](https://user-images.githubusercontent.com/82304192/185214843-fb3e67ea-17eb-4636-a13b-220b10fb385f.JPG)
:
