### ISSUE TITLE
Quality Cd quality or not 

### ISSUE THREAD

**Issue by tathastu871** [Dniel97/orpheusdl-tidal#19]
**Describe the bug**
 This tool isnt downloading lossless music. Its just downloading 320 kbps mp3 quality and encode to m4a

**To Reproduce**
 python3 orpheus.py url
Quality settings : lossless ---- 320kbps
![Screenshot_20220911-112958_Termux](https://user-images.githubusercontent.com/65007212/189514737-f319dee9-90b7-4c0a-bb48-e44efc8a60a3.jpg)
Quality Settings : hifi ---- 321kbps
![Screenshot_20220911-113102_Termux](https://user-images.githubusercontent.com/65007212/189514757-16990019-c5af-4762-a0e6-920c884d2c9e.jpg)

  **Expected behavior**
 A lossless CD-Quality rip. 

Spectrogram of Same track:

**From qobuz:** 

![Qobuz](https://user-images.githubusercontent.com/65007212/189514775-a1422788-e315-444e-8010-1a5dfe8bc279.png)

**From Tidal using orpheus.py**

![Tidal](https://user-images.githubusercontent.com/65007212/189514799-54ca74d7-58ea-4674-adf3-4beb7ba37f6f.png)

  **Screenshots**
 

  **Desktop (please complete the following information):**
  - OS: [e.g. Windows, Unix, Android]
  - Python version [e.g. 3.6.9, 3.9.3]

  **Additional context**

**Comment by yarrm80s** [comment]
@tathastu871 why did you close the issue? If you still have the issue, make sure to check your subscription is premium, and you've set your quality in the settings to lossless or hifi, and make sure that the song you're playing is actually available lossless

**Comment by yarrm80s** [comment]
to check if you can actually stream the track lossless just play it on the mobile app with lossless enabled

**Comment by tathastu871** [comment]
> to check if you can actually stream the track lossless just play it on the mobile app with lossless enabled

Sir, i have purchased premium yesterday. And track shows hifi when playing in app

**Comment by Dniel97** [comment]
You need HiFi Plus to stream Tidal Masters and Lossless, Premium only get AAC-LC.

**Comment by yarrm80s** [comment]
@Dniel97 whoops sorry that's what I meant

**Comment by tathastu871** [comment]
> You need HiFi or HiFi Plus to stream Tidal Masters and Lossless, Premium only gets AAC-LC. You can try a different track and see which quality OrpheusDL is downloading.

I have purchased hifi plus subscription

**Comment by Dniel97** [comment]
So have you tried different tracks? The track above is region locked so I cannot test that.

**Comment by tathastu871** [comment]
> So have you tried different tracks? The track above is region locked so I cannot test that.

I have tried all major tidal downloader, orpheus; tidal-dl, streamrip.   But whether its flac or mqa they aren't lossless. Their spectrogram peak at 20Hz (identical to 320kbps encoded songs)

**Comment by yarrm80s** [comment]
@tathastu871 did you try checking multiple tracks or just one?

**Comment by Dniel97** [comment]
I used the following link (for my region) to the song you provided: [https://tidal.com/browse/track/91858746](https://tidal.com/browse/track/91858746):

![SCR-20220914-g1-2](https://user-images.githubusercontent.com/6324072/190019567-47518905-2a29-4439-bffa-78dadaf620cb.png)

and downloaded in FLAC using the `"download_quality": "lossless"` and analyzed the spectrogram with SoX:

![3  Brown Rang](https://user-images.githubusercontent.com/6324072/190019704-b14684a8-258f-4bc2-8595-8cfe1ba1c270.png)

which looks identical to the Qobuz spectrogram you showed in your first issue, so I will close this issue.

**Comment by tathastu871** [comment]
whats the trick here. I am playing track on tidal it shows hifi and i shared copy link and used it.

**Comment by yarrm80s** [comment]
@tathastu871 if you recorded what Tidal was playing you'll see the same frequency response, OrpheusDL only downloads the original files the apps get

**Comment by tathastu871** [comment]
> @tathastu871 if you recorded what Tidal was playing you'll see the same frequency response, OrpheusDL only downloads the original files the apps get

?? Means

**Comment by tathastu871** [comment]
> @tathastu871 meaning this is not an issue with OrpheusDL, but rather the specific song you are trying

But dniel97 posted he was able to download lossless of same track, then why notmine

**Comment by yarrm80s** [comment]
@tathastu871 he clearly said he downloaded a different version of the track as the one you specified is not available in his region, please read what we are telling uou

**Comment by yarrm80s** [comment]
@tathastu871 try testing out the song Darkside by Alan walker
