### ISSUE TITLE
If both Dolby Atmos and 360RA are available for same track, which is downloaded?

### ISSUE THREAD

**Issue by hell001** [Dniel97/orpheusdl-tidal#20]
Which one of these take preference?

Also a side question, is every track available in AC-4 also guaranteed to be available in EAC-3? (In other words, no AC-4 only Atmos tracks on the platform?)

**Comment by yarrm80s** [comment]
Are there even any tracks on Tidal that are available in both formats...?

**Comment by Dniel97** [comment]
That is currently not possible in Tidal infrastructure, it is either Dolby Atmos OR Sony 360RA. Every Dolby Atmos track should be available in both formats AC-4 and E-AC-3 JOC.

**Comment by hell001** [comment]
> Are there even any tracks on Tidal that are available in both formats...?

It depends on what you mean by "track". If you mean the TIDAL-assigned track ID, then I haven't come across any (supports @Dniel97 's answer, thanks for the info BTW). If you otherwise mean just the song, then yes ([1](https://tidal.com/browse/album/216261500), [2](https://tidal.com/browse/album/216825105)).
