### ISSUE TITLE
TypeError Python Exceptions on album/track download attempts.

### ISSUE THREAD

**Issue by thechrisgregory** [Dniel97/orpheusdl-tidal#21]
TypeError exception on all album/track download attempts. See attachment.
![Capture](https://user-images.githubusercontent.com/28732529/193362986-3547bb84-5caa-4f21-8329-9122658e39d8.JPG)

**Comment by mexsana123** [comment]
Update Orpheus

**Comment by thechrisgregory** [comment]
Fixed.

**Comment by thechrisgregory** [comment]
Thanks
