### ISSUE TITLE
Orpheus stops at username, does not ask for password at mobile session, therefore no login possible

### ISSUE THREAD

**Issue by MarkHeat** [Dniel97/orpheusdl-tidal#26]
**Describe the bug**
Downloading stereo with non mobile session works very well, but when attempting to log in as mobile session, orpheus stops after username: 

**To Reproduce**

 $ python orpheus.py search tidal track beatles the long and wi
nding road
DEBUG:root:Orpheus: Modules detected: example, tidal
DEBUG:root:Orpheus: example added as a module
DEBUG:root:Orpheus: tidal added as a module

   ____             _                    _____  _
  / __ \           | |                  |  __ \| |
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |
             |_|

 "enable_mobile" is enabled but no MOBILE session was found. Do you want to create a MOBILE session (used for AC-4/360RA) [Y/n]? Y
DEBUG:root:TIDAL: TV session found, loading
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.tidal.com:443
DEBUG:urllib3.connectionpool:https://api.tidal.com:443 "GET /v1/sessions HTTP/1.1" 200 271
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.tidal.com:443
DEBUG:urllib3.connectionpool:https://api.tidal.com:443 "GET /v1/users/182938909/subscription HTTP/1.1" 200 290
DEBUG:root:TIDAL: No MOBILE_DEFAULT session found, creating new one
 TIDAL: Creating a Mobile session
 TIDAL: Enter your Tidal username and password:
 Username: mein.nutzername@example.de

-> thats it, no question about password....

  **Expected behavior**
There should be a password-field, then login, then download or search

  **Desktop (please complete the following information):**
  - OS: Windows 11 
  - Python version [e.g. 3.6.9, 3.9.3]

**Comment by mexsana123** [comment]
Are you running Orpheus via PyCharm by any chance? If so, try running in into CMD or Powershell. I only ever heard this issue occur when `.getpass()` is used via PyCharm window.

**Comment by MarkHeat** [comment]
Thats it, running orpheus via CMD works, but via Git Bash not. Thanks for your fast answer. i wouldn't have tried this! :-)
Was able to log into my account! Great!

Something else: is there any way to play those 360RA files via an AVR or to demux them? There are some quadraphonic rarities that would be great to be heard in 4 channel and not only stereo...

**Comment by Dniel97** [comment]
AFAIK There is currently no way to bitstream those MHA1 files to an AVR via HDMI, Chromecast only supports MHM1 wo that won't work, you can try to decode it using https://github.com/ittiam-systems/libmpegh.

**Comment by MarkHeat** [comment]
That works fantastic! Thanks for the hint! And for your help! 
Do i have to close the topic?

**Comment by Dniel97** [comment]
Your welcome, I can also close this issue.

**Comment by ahahimagine** [comment]
> Thats it, running orpheus via CMD works, but via Git Bash not. Thanks for your fast answer. i wouldn't have tried this! :-) Was able to log into my account! Great!

I've only been able to run it through Git Bash, may I ask how you able to run it through CMD? I have the same problem as you.

**Comment by ahahimagine** [comment]
@Dniel97 when I try to run a mobile session, I can enter the username and password just fine but it gives me this error: 

modules.tidal.tidal_api.TidalAuthError: {"hasInternalDetails":false,"message":"Request failed with status code 401","isApiError":true,"isAxiosError":true,"messageCode":"WRONG_USERNAME_OR_PASSWORD","status":401} 

I triple checked my login details and they should be correct. Is it because the password isn't echoed? To avoid typing it in falsely I copy and pasted my password directly from my clipboard, but I cannot get past this error.
