### ISSUE TITLE
Ayreon - Universal Migrator downloads as stereo instead of Atmos

### ISSUE THREAD

**Issue by mrmatteastwood** [Dniel97/orpheusdl-tidal#27]
**Describe the bug**
This is very similar to bug #25. When attempting to download https://listen.tidal.com/album/242428593, a stereo FLAC version is downloaded and saved as .m4a files.

**To Reproduce**
1. Use command 'python orpheus.py https://listen.tidal.com/album/242428593' with this config: https://gist.github.com/mrmatteastwood/1c6d40bf7d603cb8ab7bdfe8a5b4b294
2. Observe downloaded folder name and contents

  **Expected behavior**
The Atmos version of the album should be downloaded and stored as .m4a files.

  **Desktop (please complete the following information):**
  - OS: Linux Mint 21
  - Python version 3.10.6

  **Additional context**
My settings.json is set to put the suffix "[Dolby Atmos]" into the folder name for albums that are encoded as such. That suffix is missing from the folder title created for this album, suggesting it might not be properly recognized.
Haven't experienced this with any other Dolby Atmos encoded albums.
All packages from requirements.txt for both orpheusdl and the TIDAL module are up to date.
Deleted `loginstorage.bin` and re-connected. Same result.

**Terminal output**
```
$ python orpheus.py https://listen.tidal.com/album/242428593

   ____             _                    _____  _      
  / __ \           | |                  |  __ \| |     
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |     
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |     
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____ 
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |                                       
             |_|                                       
             

 "enable_mobile" is enabled but no MOBILE session was found. Do you want to create a MOBILE session (used for AC-4/360RA) [Y/n]? y
 TIDAL: Creating a TV session
Opening https://link.tidal.com/RAFIQ, log in or sign up to TIDAL.
Checking link      
Successfully linked!
 TIDAL: Creating a Mobile session
 TIDAL: Enter your Tidal username and password:
 Username: [redacted]
 Password: 
 Successfully logged in, using MOBILE_DEFAULT token!
 Successfully logged in, using MOBILE_ATMOS token!
=== Downloading album Universal Migrator, Pt. I & II (2022 Remixed & Remastered) (242428593) ===
        Artist: Ayreon (3658990)
        Year: 2022
        Duration: 02h:15m:53s
        Number of tracks: 20
        Service: TIDAL
        Downloading album cover

        Track 1/20
        === Downloading track The Dream Sequencer (2022 Remixed & Remastered) (242428596) ===
                Artists: Ayreon (3658990)
                Release year: 2022
                Duration: 05m:09s
                Codec: FLAC, bitrate: 732kbps, bit depth: 16bit, sample rate: 44.1kHz

                Downloading track file
                100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 79/79 [00:02<00:00, 31.30it/s]
                FFmpeg is not installed or working! Using fallback, may have errors
                Downloading artwork
                Retrieving credits
                Tagging file
        === Track 242428596 downloaded ===
```

**Comment by Dniel97** [comment]
Thats not a bug with OrpheusDL... only part 1 track 5 and part 2 track 5 are available in Dolby Atmos. To be honest that's the first time I've seen non Dolby Atmos tracks inside a Dolby Atmos album, normal TIDAL just creates the album with two tracks inside and for the other tracks you would need the other non Dolby Atmos release.

**Comment by mrmatteastwood** [comment]
You're right! I should have noticed that. I only paid attention to the "Atmos" label on the album without looking at the actual tracks inside. Thanks for following up!
