### ISSUE TITLE
The token has expired - How to fix this issue?

### ISSUE THREAD

**Issue by KatieBelli** [Dniel97/orpheusdl-tidal#28]
I can't download anything anymore. I can't remember if I changed my password some time ago but I use the default settings and didn't change anything when I installed this module.

> ...\orpheusdl-master\modules\tidal\tidal_api.py", line 339, in get_subscription
>     raise TidalAuthError(r.json()['userMessage'])
> modules.tidal.tidal_api.TidalAuthError: The token has expired. (Expired on time)
>

How can I fix this? I can download with the GUI downloader for TIDAL as usual but orpheus won't let me anymore.

**Comment by Dniel97** [comment]
The module should refresh the token automatically, so if eating like a day doesn't fix it, delete the `config/loginstorage.bin` file and try it again.

**Comment by Dniel97** [comment]
You can! Just write or copy&pasta it, the entered characters are intentionally hidden for security reasons.

**Comment by KatieBelli** [comment]
I copied & pasted my password and now this shows up:

> Traceback (most recent call last):
>   File "C:\Users\...\orpheusdl-master\orpheus.py", line 223, in <module>
>     main()
>   File "C:\Users\...\orpheusdl-master\orpheus.py", line 218, in main
>     orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
>   File "C:\Users\...\orpheusdl-master\orpheus\core.py", line 368, in orpheus_core_download
>     music = orpheus_session.load_module(mainmodule)
>   File "C:\Users\...\orpheusdl-master\orpheus\core.py", line 210, in load_module
>     loaded_module = class_(module_controller)
>   File "C:\Users\...\orpheusdl-master\modules\tidal\interface.py", line 113, in __init__
>     sessions[session_type].auth(username, password)
>   File "C:\Users\...\orpheusdl-master\modules\tidal\tidal_api.py", line 410, in auth
>     raise TidalAuthError("TIDAL BOT protection, try again later!")
> modules.tidal.tidal_api.TidalAuthError: TIDAL BOT protection, try again later!

Never had issues with a TIDAL bot so I have no idea why this happens.

**Comment by Dniel97** [comment]
Update the TIDAL module to the latest master commit.

**Comment by Dniel97** [comment]
Sure deleting the folder `modules/tidal` and entering the command `git clone --recurse-submodules https://github.com/Dniel97/orpheusdl-tidal.git modules/tidal` will work too. Did you actually cline it in the right directory, keep in mind that you need to open the OrpheusDL folder inside the CMD before you execute the command, looks like you cloned it somewhere else.

**Comment by KatieBelli** [comment]
I followed your directions but the error still exists. I even uninstalled Orpheus in general and installed it again.

**Comment by KatieBelli** [comment]
Today I changed my password on Tidal, updated the files again, removed the loginstorage.bin file and suddenly it worked. Thanks for helping me. Problem solved.

**Comment by esturniolo** [comment]
Sorry to comeback to this old post. I need to recreate my .bin file, But I don't remember how. There is some doc about it?

Thanks.
