### ISSUE TITLE
Please add support for hi-res lossless

### ISSUE THREAD

**Issue by therealshiggins** [Dniel97/orpheusdl-tidal#37]
TIDAL can now stream 24/192 lossless FLAC: https://tidal.com/sound-quality

Please can you add support to download these tracks instead of MQA

Thanks

**Comment by therealshiggins** [comment]
Excellent, that works perfectly, thank you

**Comment by coder1968** [comment]
Hi,  when I try to use this (DEV Branch),  I end up with M4a files.  Also there is an error "FFmpeg is not installed or working! Using fallback, may have errors".  The thing is FFmpeg is installed.  Is there some sort of configuration I am overlooking?

Thanks

**Comment by mesoller** [comment]
> Has been implemented since commit [5ca2f98](https://github.com/Dniel97/orpheusdl-tidal/commit/5ca2f984db59fb617e615d98e6fe11a8afd86234) (July 12th)
> 
> Update the module, switch branch to develop and delete your login storage aswell as the tidal module specific settings from the config for everything to work accordingly.

I try to understand this one. So for download_quality, sufficient with "hifi" or we need to put "HI_RES_LOSSLESS"?

**Comment by uhwot** [comment]
@mesoller use "hifi" as download quality
