### ISSUE TITLE
Tidal High Res flac

### ISSUE THREAD

**Issue by expattaxtools** [Dniel97/orpheusdl-tidal#39]
Hi, now that Tidal switched to high res flac files, is there an update planned to be able to get them instead or the MAQ versions?

**Comment by coder1968** [comment]
Hi, when I try to use this (DEV Branch), I end up with m4a files. Also there is an error "FFmpeg is not installed or working! Using fallback, may have errors". The thing is FFmpeg is installed. Is there some sort of configuration I am overlooking?  What command should I have used to get the dev branch? (git clone -b develop --recurse-submodules https://github.com/Dniel97/orpheusdl-tidal.git modules/tidal)?  I am sure it is user error :)...

Thanks
