### ISSUE TITLE
How to force Dolby Atmos Downloads to use AC-4 codec

### ISSUE THREAD

**Issue by rittennig** [Dniel97/orpheusdl-tidal#4]
How can I force the archiving tool to use AC-4 Instead of EAC-3 JOC , All the songs I try to download are in EAC-3 JOC format not AC-4.

I am new to Dolby stuff so can anyone tell me if AC-4 is good or EAC-3 JOC is good.
I heard AC-4 is good for headphones or something.

**Comment by yarrm80s** [comment]
E-AC-3 JOC is by far the better codec when compared to AC-4 IMS. Also, you probably wouldn't be able to play the AC-4 anyway
