### ISSUE TITLE
"TIDAL BOT protection" 

### ISSUE THREAD

**Issue by Issayamba** [Dniel97/orpheusdl-tidal#40]
after writing my username password I come across this problem

![image](https://github.com/Dniel97/orpheusdl-tidal/assets/97695161/08a13a82-87a9-415f-88c0-e2032f54f00f)

OBS: I'm using the free trial version HIFI Plus and I'm on Windows 10

**Comment by ISkIN-AI** [comment]
I have the same problem. By the way, I always get a captcha when logging into my account via browser.

**Comment by Dniel97** [comment]
> I have the same problem. By the way, I always get a captcha when logging into my account via browser.

Yeah that's the issue, you cannot solve a captcha using the CMD so either use the TV session or try a different PC/IP Address.
