### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by sultanmonsur** [Dniel97/orpheusdl-tidal#44]
Everything is fine. But after login to mobile session it shows try again or tidal bot protection.

![Screenshot_2023-10-26-21-43-59-57_84d3000e3f4017145260f7618db1d683](https://github.com/Dniel97/orpheusdl-tidal/assets/61897416/59db5653-e564-4c65-8f98-c177cc3c80db)

https://github.com/Dniel97/orpheusdl-tidal/assets/61897416/44df5fbc-c3c9-4ca1-a7df-e3fbf47f7688

**Comment by ISkIN-AI** [comment]
https://github.com/Dniel97/orpheusdl-tidal/issues/40#issuecomment-1712907945

**Comment by sultanmonsur** [comment]
Not working 😭
