### ISSUE TITLE
Tidal Master - understanding question - Is the download master or MQA - what is the different?

### ISSUE THREAD

**Issue by anjoku** [Dniel97/orpheusdl-tidal#5]
Hi there,
I got quite far and was able to download a few things.
I have a HIFI Plus subscription and would like to download the songs in High Res.
Seems like it works and it's master quality. But where is the difference to MQA.
Can I somehow achieve that the best possible quality is loaded.

Best regards
Andre

Here my settings:
{
    "global": {
        "general": {
            "download_path": "./downloads/",
            "download_quality": "hifi",
            "search_limit": 10
        },
        "artist_downloading": {
            "return_credited_albums": true,
            "separate_tracks_skip_downloaded": true
        },
        "formatting": {
            "album_format": "{artist}/{name} [{release_year}] {quality}{explicit}",
            "playlist_format": "{name}{explicit}",
            "track_filename_format": "{track_number} - {name} - {artist} {explicit}",
            "single_full_path_format": "Singles/{track_number}  - {name} - {artist} {explicit}",
            "enable_zfill": true
        },
        "codecs": {
            "proprietary_codecs": true,
            "spatial_codecs": true
        },
        "module_defaults": {
            "lyrics": "default",
            "covers": "default",
            "credits": "default"
        },
        "lyrics": {
            "embed_lyrics": true,
            "save_synced_lyrics": true
        },
        "covers": {
            "main_compression": "high",
            "main_resolution": 1400,
            "save_external": false,
            "external_format": "png",
            "external_compression": "low",
            "external_resolution": 3000,
            "save_animated_cover": true
        },
        "advanced": {
            "advanced_login_system": false,
            "codec_conversions": {
                "alac": "flac"
            },
            "conversion_flags": {
                "flac": {
                    "compression_level": "5"
                }
            },
            "conversion_keep_original": false,
            "cover_variance_threshold": 8,
            "debug_mode": false,
            "disable_subscription_checks": false,
            "enable_undesirable_conversions": false,
            "ignore_existing_files": false,
            "ignore_different_artists": true
        }
    },
    "extensions": {},
    "modules": {
        "tidal": {
            "tv_token": "7xxxxxxxxxxxxxxxxxxxxxn",
            "tv_secret": "vRxxxxxxxxxxxxxxxxxxxxx9saEzsgY=",
            "mobile_token": "dxxxxxxxxxxxxxxxxllu4",
            "enable_mobile": false,
            "prefer_ac4": false
        }
    }
}

**Comment by Dniel97** [comment]
So I highly suggest reading: [https://support.tidal.com/hc/en-us/articles/115000397069-TIDAL-Masters-and-Master-Quality-Audio](https://support.tidal.com/hc/en-us/articles/115000397069-TIDAL-Masters-and-Master-Quality-Audio) which tells you that `Tidal Masters` uses the `MQA` (**M**aster **Q**uality **A**uthenticated codec). Checking out [https://github.com/Dniel97/orpheusdl-tidal#global](https://github.com/Dniel97/orpheusdl-tidal#global) tells you that you need 
```
"download_quality": "hifi"
```
and 
```
 "proprietary_codecs": true
```
in order to get MQA and of course a `Tidal Masters` album/track link. So your config seems perfectly fine to me and if OrpheusDL shows you the Codec `MQA` you also know that it worked just fine.

**Comment by Dniel97** [comment]
Closing, no further information provided.
