### ISSUE TITLE
Some tracks can't be downloaded in MQA Codec

### ISSUE THREAD

**Issue by Andrea-lyz** [Dniel97/orpheusdl-tidal#51]
This is my json:
"codecs": { "proprietary_codecs": true, "spatial_codecs": false

"enable_mobile": true, "force_non_spatial": false, "prefer_ac4": false, "fix_mqa": true

Problem tracks : https://tidal.com/album/331653715
=== Downloading track You’re Losing Me (From The Vault) (331653717) === Artists: Taylor Swift (3557299) Release year: 2023 Duration: 04m:38s Codec: FLAC, bitrate: 1543kbps, bit depth: 24bit, sample rate: 48.0kHz Downloading track file 100%|███████████████████████████████████████████████████████████████████| 72/72 [00:02<00:00, 34.33it/s] Downloading artwork Retrieving lyrics with musixmatch Retrieving credits Tagging file === Track 331653717 downloaded ===

When I try other tracks, it downloads MQA correctly, for example : https://tidal.com/album/282033424
=== Downloading track All Of The Girls You Loved Before (282033425) === Artists: Taylor Swift (3557299) Release year: 2023 Duration: 03m:41s Codec: MQA, bit depth: 24bit, sample rate: 44.1kHz Downloading track file 100%|██████████████████████████████████████████████████████████████| 40.2M/40.2M [00:00<00:00, 44.2MB/s] Downloading artwork Retrieving lyrics with musixmatch Retrieving credits Tagging file === Track 282033425 downloaded ===

I also tried the Tidal-dl project and was able to correctly download the MQA code for the track(331653717).

**Comment by Dniel97** [comment]
You don't! Why would you want a lossy proprietary codec in lower quality than a lossless open source HiRes FLAC file?

**Comment by OrfiDev** [comment]
@Andrea-lyz but the MQA version is almost certainly just based on the 24 bit version, it would be like collecting MP3's alongside whatever lossless stuff you download, except MQA's are not very easy to even play "properly"

**Comment by Andrea-lyz** [comment]
@OrfiDev I often use USB Audio Player PRO to 2x expand MQA on mobile devices, plus some DAC devices with decoders, and sometimes I can get some good results, especially the blue-marked MQA.

**Comment by OrfiDev** [comment]
@Andrea-lyz but that's like saying that you took a photo with a digital camera, and then printed it, but your scanner is very good at scanning that print. Why on Earth would you want to play the print version instead of the original file, when you can get the original file?

**Comment by Dniel97** [comment]
> @OrfiDev I often use USB Audio Player PRO to 2x expand MQA on mobile devices, plus some DAC devices with decoders, and sometimes I can get some good results, especially the blue-marked MQA.

"blue-marked" MQA files or "Studio" MQA files have just the provenance bit flag higher than 8 (https://github.com/Dniel97/MQA-identifier-python/blob/ff0c9f1824d471d95ee8faf88af19325dc617d90/mqa_identifier_python/mqa_identifier.py#L158) lol. That is just placebo and doesn't indicate better audio AT ALL.

**Comment by Andrea-lyz** [comment]
@OrfiDev I understand, thanks for your work
