### ISSUE TITLE
Is manual login still required for 360?

### ISSUE THREAD

**Issue by hell001** [Dniel97/orpheusdl-tidal#52]
It's been awhile since I updated this module, and it seems some things were changed.

**Previously**, when logging in it would request you to login at tidal.com. Then, for 360, it would have you again login but this time manually to create a mobile session.

**Now**, it _asks_ which way you want to log in (browser or manual). I chose browser and logged in the way I previously have. However, it no longer prompts me to manually log in to download 360 content.

Does this mean manual login is no longer required for 360 like it previously was? I thought a mobile session was required for 360, but I logged in with browser/"TV"? Should I delete loginstorage.bin and choose the mobile login option instead just in case?

**Comment by OrfiDev** [comment]
@hell001 why didn't you just try downloading a 360 track? Anyway, the process is a lot more streamlined now

**Comment by uhwot** [comment]
@hell001 the module logs into the other sessions automagically now, you just have to login once and it takes care of the rest

**Comment by hell001** [comment]
> @hell001 why didn't you just try downloading a 360 track? Anyway, the process is a lot more streamlined now



> @hell001 the module logs into the other sessions automagically now, you just have to login once and it takes care of the rest

Thanks both. before posting i did try to download a 360 track and it worked. i was mainly asking just for confirmation, as the readme says that username and password login is still required for the enable_mobile session

**Comment by hell001** [comment]
Still hoping to get clarification on this. The docs for enable_mobile says

> Enables a second MOBILE session **which needs a username and password** (can be the same "TV" account) to archive **Sony 360RA** and Dolby AC-4 if available or allows force_non_spatial to work properly

can anyone confirm this is no longer true? @Dniel97

**Comment by Dniel97** [comment]
> > @hell001 why didn't you just try downloading a 360 track? Anyway, the process is a lot more streamlined now
> 
> > @hell001 the module logs into the other sessions automagically now, you just have to login once and it takes care of the rest
> 
> Thanks both. before posting i did try to download a 360 track and it worked. i was mainly asking just for confirmation, as the readme says that username and password login is still required for the enable_mobile session (which i did not do)

Well you already answered your own question and it has been answered by @uhwot as well.
