### ISSUE TITLE
Certain track downloading in only AC-4 IMS.

### ISSUE THREAD

**Issue by gahtv** [Dniel97/orpheusdl-tidal#54]
**Describe the bug**
When downloading a track from Tidal (like [this one](https://tidal.com/browse/track/314664004)), it only downloads in AC-4, even when i have "prefer_ac4" in config.json set to false.

**To Reproduce**
 1. Use command 'python .\orpheus.py https://tidal.com/browse/playlist/096e634f-4af6-48e4-b8c0-615b5b82eaf5' (playlist of what i wanted to download)
 2. When you download track 6 and 9, they both download in AC-4 IMS.

  **Expected behavior**
I expected when I download that track to be in AC-3 JOC, as I have no AC-4 decoder and have set "prefer_ac4" in config.json set to false.

  **Screenshots**
 If applicable, add screenshots to help explain your problem or to show the error message.
![image](https://github.com/Dniel97/orpheusdl-tidal/assets/20805878/52d6d4df-8f6e-4f75-9365-7a756027610b)
![image](https://github.com/Dniel97/orpheusdl-tidal/assets/20805878/aea51f3d-b610-41d5-b0d5-d53c6a4055f4)
![Screenshot 2024-01-03 154340](https://github.com/Dniel97/orpheusdl-tidal/assets/20805878/d2301271-a29f-41a0-a3ac-455dd53b7ef4)
  **Desktop (please complete the following information):**
  - OS: Windows 11 Pro Insider Preview (Build 26016.rs_prerelease.231208-1532)
  - Python version: 3.10.11

**Additional Context**

This only seems (?) to be for this track, I'll also download [this playlist](https://tidal.com/browse/playlist/cff794ca-15cf-4740-a0b3-ad9eb34e3f2c) and add to the issue if any songs here download in AC-4.

**Comment by gahtv** [comment]
[Here (playlist1)](https://tidal.com/browse/playlist/fc5d0afd-e51b-4076-bcf3-c78b5041d754) is a list of tracks when downloading [Best of 2023: Dolby Atmos](https://tidal.com/browse/playlist/cff794ca-15cf-4740-a0b3-ad9eb34e3f2c) with mobile token downloads in AC-4. However, when I download [playlist1](https://tidal.com/browse/playlist/fc5d0afd-e51b-4076-bcf3-c78b5041d754) with the tv token, it downloads in AC-3, which is a temporary solution; just download tracks in tv mode if an AC-4 track/album comes my way. 

This is a bit clumsy though; for example, if a 24 bit flac appears with one of these tracks in a playlist, you'd have to first download the playlist in mobile mode, and download the offending tracks in tv mode (eg. what I did to [BO2023: DA](https://tidal.com/browse/playlist/cff794ca-15cf-4740-a0b3-ad9eb34e3f2c) with [playlist1](https://tidal.com/browse/playlist/fc5d0afd-e51b-4076-bcf3-c78b5041d754)), so a toggle off AC4 entirely somehow could be useful? If not, I can live with a bit of clumsyness.

TIA!

**Comment by uhwot** [comment]
This is already fixed in the develop branch, it just hasn't been merged to master yet
In the meantime, do `git switch develop` and `git pull` while in the Tidal module directory and it should work fine

**Comment by gahtv** [comment]
Switching to the develop branch has me not downloading AC-4, however it has now got me downloading FLACs, when I would like to download the atmos version of the track.

In the definition for get_track_info(), there's a comment that says "if atmos is available, we don't use the TV session here because that will get atmos everytime", but could you not use "spatial_codecs" to determine whether the user would like to download a FLAC or an Atmos version? Or, if it is written that way because HiRes FLAC > Atmos to most users most of the time, could you not put a boolean in the module config to change the inequality? I think I'm in the minority of wanting Atmos over HiRes FLAC, but would be better.

**Comment by uhwot** [comment]
It's written that way since people prefer Hires FLAC over Atmos most of the time, you can change the download quality to something other than "hifi" and it should download the Atmos file instead

Though if you want both Hires and Atmos files on a playlist it's kinda awkward for now, maybe i should add an option for that or something

**Comment by Dniel97** [comment]
Fixed, as of commit f63b916.
