### ISSUE TITLE
Download the 24/48 file with the suffix. m4a?

### ISSUE THREAD

**Issue by toddchan1713** [Dniel97/orpheusdl-tidal#56]
Download a 24/48 file with a. m4a suffix, but when playing, foobar still shows flac. Why is this?

**Comment by Dniel97** [comment]
Because it's a FLAC codec inside an MPEG-4 container. You should update the module to the lastet version and install ffmpeg to use the correct FLAC container.

**Comment by toddchan1713** [comment]
> 因为它是 MPEG-4 容器内的 FLAC 编解码器。您应该将模块更新到 lastet 版本并安装 ffmpeg 以使用正确的 FLAC 容器。

Excuse me, where should ffmpeg be installed?

**Comment by Dniel97** [comment]
Wherever, just make sure the bin folder is added your your environment variables PATH.
