### ISSUE TITLE
Song doesn't show up in Spotify's local files playlist

### ISSUE THREAD

**Issue by Mantas22XYT** [Dniel97/orpheusdl-tidal#57]
**Describe the bug**
Downloaded song does not show up in Spotify using the Local Files feature.

**To Reproduce**
 1. Use appropriate steps to download song;
 2. Put in a folder use by Local FIles
 3. Song doesn't show up

  **Expected behavior**
The file should show up as normal

  **Screenshots**
Not applicable?

  **Desktop (please complete the following information):**
  - OS: Windows 10 [e.g. Windows, Unix, Android]
  - Python version: 3.11.1 [e.g. 3.6.9, 3.9.3]

  **Additional context**
Songs downloaded from Deezer and SoundCloud show up fine.

**Comment by Dniel97** [comment]
Seems just like the same issue as #56. As this is not directly connected the module I will close this issue.
