### ISSUE TITLE
Can't download 24bit flacs.

### ISSUE THREAD

**Issue by CuteZombie7** [Dniel97/orpheusdl-tidal#58]
**Describe the bug**
Some albums are available in 24bit, but the program can only download 16bit. For example, this album: https://tidal.com/browse/album/288659878
"download_quality" has been set to 'hifi' and "proprietary_codecs" has been set to true.

  **Expected behavior**
Download the 24bit version flacs.

  **Desktop (please complete the following information):**
  - OS: windows
  - Python version 3.11

**Comment by Dniel97** [comment]
Update the module to the latest commit and delete loginstorage.bin to recreate your TIDAL sessions.

**Comment by CuteZombie7** [comment]
> Update the module to the latest commit and delete loginstorage.bin to recreate your TIDAL sessions.

It doesn't work.

**Comment by uhwot** [comment]
Make sure "enable_mobile" is set to true and that your account has a HiFi Plus sub.

**Comment by CuteZombie7** [comment]
> Make sure "enable_mobile" is set to true and that your account has a HiFi Plus sub.

still not work, here's my config:
`"global": {
        "general": {
            "download_path": "./downloads/",
            "download_quality": "hifi",
            "search_limit": 10
        },
        "artist_downloading": {
            "return_credited_albums": true,
            "separate_tracks_skip_downloaded": true
        },
        "formatting": {
            "album_format": "{name}",
            "playlist_format": "{name}{explicit}",
            "track_filename_format": "{name}",
            "single_full_path_format": "{name}",
            "enable_zfill": true,
            "force_album_format": false
        },
        "codecs": {
            "proprietary_codecs": true,
            "spatial_codecs": true
        },
        "module_defaults": {
            "lyrics": "default",
            "covers": "default",
            "credits": "default"
        },
        "lyrics": {
            "embed_lyrics": true,
            "embed_synced_lyrics": false,
            "save_synced_lyrics": false
        },
        "covers": {
            "embed_cover": true,
            "main_compression": "high",
            "main_resolution": 1400,
            "save_external": false,
            "external_format": "png",
            "external_compression": "low",
            "external_resolution": 3000,
            "save_animated_cover": true
        },
        "playlist": {
            "save_m3u": true,
            "paths_m3u": "absolute",
            "extended_m3u": true
        },
        "advanced": {
            "advanced_login_system": false,
            "codec_conversions": {
                "alac": "flac",
                "wav": "flac"
            },
            "conversion_flags": {
                "flac": {
                    "compression_level": "5"
                }
            },
            "conversion_keep_original": false,
            "cover_variance_threshold": 8,
            "debug_mode": false,
            "disable_subscription_checks": false,
            "enable_undesirable_conversions": false,
            "ignore_existing_files": false,
            "ignore_different_artists": true
        }
    }
`
`            "enable_mobile": true,
            "force_non_spatial": false,
            "prefer_ac4": false,
            "fix_mqa": false
`

**Comment by Dniel97** [comment]
Make sure to update the OrpheusDL-TIDAL module to the latest commit #9e29b24.

**Comment by CuteZombie7** [comment]
> Make sure to update the OrpheusDL-TIDAL module to the latest commit [9e29b24](https://github.com/Dniel97/orpheusdl-tidal/commit/9e29b24ef18d288387bed3e4edc44102e9a9b639).

solved, thank you.

**Comment by CuteZombie7** [comment]
> Make sure to update the OrpheusDL-TIDAL module to the latest commit [9e29b24](https://github.com/Dniel97/orpheusdl-tidal/commit/9e29b24ef18d288387bed3e4edc44102e9a9b639).

But the download speed of the latest version has significantly decreased.

**Comment by Dniel97** [comment]
Do you want HiRes or not? lol

**Comment by CuteZombie7** [comment]
I do want HiRes. But some albums are only available in 16bit, in this case, using old method to download may be better. The new downloading method is too slow.
