### ISSUE TITLE
Only 100 title's get Downloaded

### ISSUE THREAD

**Issue by markus681** [Dniel97/orpheusdl-tidal#6]
**Describe the bug**
Only 100 title's get Downloaded when downloading a AudioBook with 277 title.

**To Reproduce**
 1. Use command 'python3 orpheus.py https://listen.tidal.com/album/85110891'
 2. Choose '....' (only needed for search)
 3. See error

  **Expected behavior**
That AudioBook contains about 277 title's, so it should Download that complete Album.

  **Screenshots**
 If applicable, add screenshots to help explain your problem or to show the error message.
```
markus@bigeddy:~/orpheusdl$ python3 orpheus.py https://listen.tidal.com/album/85110891

   ____             _                    _____  _      
  / __ \           | |                  |  __ \| |     
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |     
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |     
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____ 
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |                                       
             |_|                                       
             

        Refreshing token successful
=== Downloading album Excess - Verschwörung zur Weltregierung (Ungekürzt) (85110891) ===
        Artist: Mathias Frey (9584821)
        Year: 2015
        Number of tracks: 100
        Service: Tidal
```
  **Desktop (please complete the following information):**
  - OS: Ubuntu 20.04.3 / Linux
  - Python version 3.8.10

  **Additional context**

**Comment by Dniel97** [comment]
Thanks for the heads up, that's indeed a problem with the API which only returns the first 100 tracks, so in order to get all - a new API function for the other tracks is needed. Will check it out!

**Comment by markus681** [comment]
If i may, i could you give a hint, i am using also a another downloader, there it works, called "tidal-dl" also python
can found here...
```
https://github.com/yaronzz/Tidal-Media-Downloader-PRO
```
