### ISSUE TITLE
using in google colab

### ISSUE THREAD

**Issue by junmittens2004** [Dniel97/orpheusdl-tidal#60]
Is it possible to use it in google colab?
If so, could you explain how I should proceed?

**Comment by Dniel97** [comment]
Please do NOT use Google Colab, thanks!

**Comment by OrfiDev** [comment]
@nervousguy2000 Why would you even ever want to do that? It sounds crazy inconvenient and OrpheusDL can run on pretty much anything if you set your mind to it
