### ISSUE TITLE
Account does not have a HiFi (Plus) subscription, detected subscription: PREMIUM

### ISSUE THREAD

**Issue by tm1uk** [Dniel97/orpheusdl-tidal#62]
Tidal have just updated existing subscriptions from HiFi Plus to Premium as the old tier has been removed. 

Since this changed for me yesterday I can no longer download anything as I get this error and I'm prompted to login again:

<img width="653" alt="image" src="https://github.com/Dniel97/orpheusdl-tidal/assets/163402006/48e85a26-c410-4f85-9608-c66f93f48438">

I've tried changing my settings.json from HiFi to lossless but still get the same issue.

I'm guessing this is because of the new tier that tidal have assigned to these subscriptions now? 

Is there any work around?

Thanks
Simon

**Comment by Dniel97** [comment]
Already fixed in 9517445 ;)
