### ISSUE TITLE
Unable to download music videos from tidal

### ISSUE THREAD

**Issue by JonnyGators** [Dniel97/orpheusdl-tidal#63]
**Describe the bug**
Unable to find a working method of downloading music videos from tidal

**To Reproduce**
 1. follow instructions "Just call orpheus.py with any link you want to archive:" using link of tidal video, such as https://tidal.com/browse/video/26760510.  This results in an Invalid URL error, despite the URL being confirmed as valid and accurate.
  **Expected behavior**
Download video from link.

  **Screenshots**
 If applicable, add screenshots to help explain your problem or to show the error message.

  **Desktop (please complete the following information):**
  - OS: [e.g. Windows, Unix, Android]
  - Python version [e.g. 3.6.9, 3.9.3]

  **Additional context**

**Comment by Dniel97** [comment]
Music video archiving is not (yet?) available in OrpheusDL in general so it's not possible to grab them using the OrpheusDL-tidal module.

**Comment by JonnyGators** [comment]
So instead of fixing the issue by adding that, you close it?

**Comment by Dniel97** [comment]
Yes because you described it as a bug and not as a feature request :)

And it is intended behavior and not a bug. I don't have the time to add this feature at the moment and it has to be added to OrpheusDL first as well.

**Comment by JonnyGators** [comment]
I would have selected feature request if that was an option. I didn't find
how. You can't convert it or resubmit it as one?

**Comment by JonnyGators** [comment]
Has this been added as a feature request?
