### ISSUE TITLE
After the change in license downloading dolby athmos is no longer working

### ISSUE THREAD

**Issue by dominiquevocat** [Dniel97/orpheusdl-tidal#64]
Downloading an album with setting to dolby atmos fails with this message:

```
 TIDAL: Account does not have a HiFi (Plus) subscription, detected subscription: PREMIUM
 Do you want to relogin? [Y/n]: n
 Exiting...
```

The change in licenses necessitates a change in the license check i suppose.

**Comment by uhwot** [comment]
this was fixed a month ago, it has nothing to do with dolby atmos
just update the module and it should be working then

**Comment by dominiquevocat** [comment]
Thanks, i should have browsed the commit history :-( - i only saw that last commit is two months old and judged it too old. My bad.

**Comment by uhwot** [comment]
no worries lol :D
