### ISSUE TITLE
ImportError: cannot import name 'Error' from 'ffmpeg' (unknown location)

### ISSUE THREAD

**Issue by toddchan1713** [Dniel97/orpheusdl-tidal#65]
todd@chentaodeMac-mini orpheusdl % ffmpeg -version
ffmpeg version 7.0 Copyright (c) 2000-2024 the FFmpeg developers
built with Apple clang version 15.0.0 (clang-1500.3.9.4)
configuration: --prefix=/usr/local/Cellar/ffmpeg/7.0 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
todd@chentaodeMac-mini orpheusdl % python3 orpheus.py
Traceback (most recent call last):
  File "/Users/todd/OrpheusDL/orpheus.py", line 7, in <module>
    from orpheus.core import *
  File "/Users/todd/OrpheusDL/orpheus/core.py", line 4, in <module>
    from orpheus.music_downloader import Downloader
  File "/Users/todd/OrpheusDL/orpheus/music_downloader.py", line 7, in <module>
    from ffmpeg import Error
ImportError: cannot import name 'Error' from 'ffmpeg' (unknown location)
todd@chentaodeMac-mini orpheusdl % 

ffmpeg was installed and ran successfully, but there was an error executing 'python3 orpheus. py', and reinstalling orpheusdl is also not possible.

**Comment by toddchan1713** [comment]
Solved, issue with environment variable configuration.

**Comment by jaime-gacitua** [comment]
Hi @toddchan1713 I have same issue how did you solve?

**Comment by Dniel97** [comment]
@jaime-gacitua 
I would check if you have any installed python module with the name "ffmpeg":
```
pip list
```
and then just perform an

```
pip uninstall ffmpeg
```
And reinstall all OrpheusDL dependencies again using
```
pip install -r requirements.txt
```
.

**Comment by toddchan1713** [comment]
To configure the path of ffmpeg in the variable environment
发自我的 iPhone

在 2024年11月3日，22:39，Jaime Gacitua ***@***.***> 写道：

﻿

Hi @toddchan1713<https://github.com/toddchan1713> I have same issue how did you solve?
