### ISSUE TITLE
24 Bit not working after recent Tidal changes

### ISSUE THREAD

**Issue by HeyMeco** [Dniel97/orpheusdl-tidal#68]
**Describe the bug**
With settings set to hifi it only downloads 16bit 44.1khz but the source is available in "MAX" in this case 24bit 44.1khz

  **Expected behavior**
 Downloaded Result in MediaInfo should show 24bit

  **Desktop**
  - OS: [MacOS]
  - Python version [3.12]

  **Additional context**
Other projects with the same issue:
- https://github.com/yaronzz/Tidal-Media-Downloader/issues/1161
- https://github.com/nathom/streamrip/issues/691

**Comment by uhwot** [comment]
24bit works fine on my end
make sure "enable_mobile" in the settings is set to true then try again, if that doesn't work send the track URL here

**Comment by HeyMeco** [comment]
I cant reproduce it anymore, seems to work again (I had enable_mobile already set to true).

**Comment by iamhongliang** [comment]
> 24bit works fine on my end make sure "enable_mobile" in the settings is set to true then try again, if that doesn't work send the track URL here

hi, I wondered where to modify the settings with "enable_mobile".
