### ISSUE TITLE
download album in to artist folder?

### ISSUE THREAD

**Issue by dejl** [Dniel97/orpheusdl-tidal#71]
Hi

How do I force download albums in to Downloads/< album artist name >/< album name >?
Right now I have tried "force_album_format": true which helps put singles in a folder but I'm unsure how to ensure when i try downloading an album to save in the relevant artist name folder?

thanks

**Comment by dwaris** [comment]
Hi, I had the same problem and in my fork is this commit to solve it: https://github.com/dwaris/orpheusdl/commit/31de6a1bce7d4f5a4b0ab98b89943e9de488fa1b
**If an album has multiple artists, it takes the first one as folder name.** 
I once asked if anybody is interested in this featuring, but nobody replied. The problem with my commit is that different providers use different characters to split multiple album artists, but mine just splits at "," which works for Tidal.

**Comment by Dniel97** [comment]
Sure its simple as:
```json
        "formatting": {
            "album_format": "{artist}/{name}{explicit}{quality}",
        }
```

**Comment by Dniel97** [comment]
> Hi, I had the same problem and in my fork is this commit to solve it: [dwaris/orpheusdl@31de6a1](https://github.com/dwaris/orpheusdl/commit/31de6a1bce7d4f5a4b0ab98b89943e9de488fa1b)
> **If an album has multiple artists, it takes the first one as folder name.**
> I once asked if anybody is interested in this featuring, but nobody replied. The problem with my commit is that different providers use different characters to split multiple album artists, but mine just splits at "," which works for Tidal.

That is not needed as the album_format supports already the `{artist}` variable.

**Comment by dejl** [comment]
> Sure its simple as:
> 
> ```json
>         "formatting": {
>             "album_format": "{artist}/{name}{explicit}{quality}",
>         }
> ```

it works except if you download a full artist it will lay out like : Downloads/< Artist name >/< artist name >/< album name >
