### ISSUE TITLE
Tidal Key

### ISSUE THREAD

**Issue by marcobibichan** [Dniel97/orpheusdl-tidal#76]
Does anyone know how to obtain the tokens? The web seems do not have any tutorial about it. 
![Uploading Screenshot_20241226_150056_com_brave_browser_ChromeTabbedActivity.jpg…]()

**Comment by Drey563** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by OrfiDev** [comment]
No way a GitHub scam link in a reply to an issue?! Edit: now it's gone, wow I've never seen that before

**Comment by Dniel97** [comment]
There will be no help getting the client_id or client_secret. Use the provided client_ids by OrpheusDL-tidal.
