### ISSUE TITLE
Sound quality not match

### ISSUE THREAD

**Issue by marcobibichan** [Dniel97/orpheusdl-tidal#78]
**Describe the bug**

**To Reproduce**
 1. Use command '...'
 2. Choose '....' (only needed for search)
 3. See error

  **Expected behavior**

  **Screenshots**
 If applicable, add screenshots to help explain your problem or to show the error message.

  **Desktop (please complete the following information):**
  - OS: [e.g. Windows, Unix, Android]
  - Python version [e.g. 3.6.9, 3.9.3]

  **Additional context**
I used "tv" method to log in and I have set download quality to "hifi" and the track was available in "max" quality in Tidal, but the flac downloaded was only in 16-bit depth, can you help me fix it?
![Screenshot_20241226_215205_com_termux_TermuxActivity.jpg](https://github.com/user-attachments/assets/f327b2db-9f40-47a1-a725-1d6aa9a3b2bd)

![Screenshot_20241226_215230_ru_zdevs_zarchiver_pro_ZTextEditor.jpg](https://github.com/user-attachments/assets/c64ca36e-e7b5-42b0-a327-e1a166c82f2d)

![Screenshot_20241226_215457_com_brave_browser_ChromeTabbedActivity.jpg](https://github.com/user-attachments/assets/2595e927-ae3d-4bb9-ad8f-e4fc4f84914a)

**Comment by marcobibichan** [comment]
Also can you tell me how to login with other accounts, I cannot change accounts once executed the python script.

**Comment by Dniel97** [comment]
Use the same link in the Tidal mobile or Desktop app and click on the small "MAX" icon, it will show you the current quality. If the quality is 44.1 kHz 16bit than OrpheusDL cannot get a higher quality as well.

**Comment by marcobibichan** [comment]
![Screenshot_20241226_230115_com_aspiro_tidal_MainActivity](https://github.com/user-attachments/assets/8979b7a5-a131-4fc4-9380-1ab904b7fd8e)
It is 24bit 96 kHz

**Comment by Dniel97** [comment]
After seeing that you tried to change the tokens. I would recommend you delete settings.json and logintorage.bin and try it again.

**Comment by marcobibichan** [comment]
Finally, I get the right sound quality, thank you so much. But, just two problem, can you tell me how to relogin? And I still cannot login through 'app' method, but it is ok to login through "tv" method.

**Comment by Dniel97** [comment]
It doesn't matter really, your IP has been blocked by Tidal, so either solve the captcha or try a VPN.
