### ISSUE TITLE
Cannot play 360RA track in VLC

### ISSUE THREAD

**Issue by omdev420** [Dniel97/orpheusdl-tidal#8]
Hey devs,
I just started using orpheusdl with tidal module to download a 360RA track but could not play it on my desktop as VLC crashes instantly.
EAC-3 tracks are playing prefect fine though.

----------------------------------------------------------------------------------

tidal module commit hash: dff7758cabe8278130ee425eb0ee386418ca2587
orpheusdl commit hash: fa5963157ac97d89cd7691584c65dbfbdb3fe1bf

**Comment by Dniel97** [comment]
Currently not possible to play it back on Windows, see here: https://github.com/Dniel97/RedSea/issues/6

**Comment by cumbreadsticks** [comment]
@omdev420 My pc isn't working pls help 😂

**Comment by omdev420** [comment]
> @omdev420 My pc isn't working pls help 😂

Could you please elaborate more on this
